const lunch = [
    {
        id: 1,
        img: '/images/lunch-img.png',
        title: 'Бізнес-ланч “Рибний"',
        weight: "250",
        calories: "346",
        info1: '1. Курячий бульйон з локшиною та яйцем ',
        info2: '2. Смажений рис з куркою ',
        info3: '3. Овочевий салат з базиліково-медовою заправкою',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 2,
        img: '/images/lunch-img2.png',
        title: 'Бізнес-ланч “М’ясний”',
        weight: "250",
        calories: "346",
        info1: '1. Курячий бульйон з локшиною та яйцем ',
        info2: '2. Смажений рис з куркою ',
        info3: '3. Овочевий салат з базиліково-медовою заправкою',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 3,
        img: '/images/lunch-img.png',
        title: 'Бізнес-ланч “Рибний"',
        weight: "250",
        calories: "346",
        info1: '1. Курячий бульйон з локшиною та яйцем ',
        info2: '2. Смажений рис з куркою ',
        info3: '3. Овочевий салат з базиліково-медовою заправкою',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 4,
        img: '/images/lunch-img2.png',
        title: 'Бізнес-ланч “М’ясний”',
        weight: "250",
        calories: "346",
        info1: '1. Курячий бульйон з локшиною та яйцем ',
        info2: '2. Смажений рис з куркою ',
        info3: '3. Овочевий салат з базиліково-медовою заправкою',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 5,
        img: '/images/lunch-img.png',
        title: 'Бізнес-ланч “Рибний"',
        weight: "250",
        calories: "346",
        info1: '1. Курячий бульйон з локшиною та яйцем ',
        info2: '2. Смажений рис з куркою ',
        info3: '3. Овочевий салат з базиліково-медовою заправкою',
        count: 0,
        price: 189,
        priceTotal: 0,
    },
    {
        id: 6,
        img: '/images/lunch-img2.png',
        title: 'Бізнес-ланч “М’ясний”',
        weight: "250",
        calories: "346",
        info1: '1. Курячий бульйон з локшиною та яйцем ',
        info2: '2. Смажений рис з куркою ',
        info3: '3. Овочевий салат з базиліково-медовою заправкою',
        count: 0,
        price: 189,
        priceTotal: 0,
    },

];

export default lunch;
